version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  
  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: postgres
    volumes:
      - .:/onebitexchange
      - gems:/gems
    depends_on:
      - db

volumes:
  postgres:
  gems: